### ISSUE TITLE
zoxide package

### ISSUE THREAD

**Issue by Heus-Sueh** [ublue-os/aurora#60]
### Describe the package

I would like to request that the [zoxide](https://github.com/ajeetdsouza/zoxide) package to be included in the image by default.

It is a smarter cd command that supports all major shells. It has become something extremely necessary for me in particular, it allows you to navigate between directories much faster without having to type an entire path, sometimes a keyword is enough.
### Image

All Images

**Comment by RealVishy** [comment]
Install it with brew

**Comment by Heus-Sueh** [comment]
> Install it with brew or run the ujust for aurora-cli

I wasn't clear, sorry.
The issue is about including it directly in the image by default

**Comment by ledif** [comment]
Command-line developer productivity apps such as `zoxide` (which ublue folks sometimes refer to as bling) are by design not shipped in the image themselves, but are included in a Brewfile that users can install with `ujust aurora-cli`.

`zoxide` is already included in the list of bling, so it should be installed if you run that command.

https://github.com/ublue-os/aurora/blob/76566fa3c3d90b5c760e25f3c928b64499d23e7c/system_files/shared/usr/share/ublue-os/homebrew/aurora-cli.Brewfile#L5-L15
